title: "EQUIGEN: Few-shot Implicit Function Generation via Equivariance"
description: "Project page for the CVPR 2025 Highlight paper , focusing on few-shot implicit function generation via equivariance."