model:
  hidden_dim: 128
  input_features: 1

  transformer_config:
    n_embd: 2048
    n_layer: 12
    n_head: 16
    split_policy: layer_by_layer
    use_global_residual: False
    attn_pdrop: 0

  scheduler_config:
    num_train_timesteps: 1000
    beta_schedule: "squaredcos_cap_v2"
    clip_sample: false
    set_alpha_to_one: false
    steps_offset: 1

  train_feature_extractor: True
  n_classes: 9
  feature_extractor_path: 

training:
  batch_size: 32 
  num_epochs: 6000 
  learning_rate: 2e-4
  weight_decay: 2e-5
  save_every: 2000 
  eval_every: 8000
  loss_function: 'mse'
  scheduler_step: 250
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0 
  num_workers: 8
  checkpoint_path:

data:
  dataset: "mnist"

is_few_shot: False

wandb:
  enabled: True

seed: 42
gpu: 0,1
mixed_precision: "no"

hydra:
  job:
    chdir: false

few_shot:
  dataset: "mnist_9_10"
  training:
    batch_size: 10  
    num_epochs: 250 
    eval_every: 500
    lamb: 0.1
